### ISSUE TITLE
Code Basic Player Mechanics

### ISSUE THREAD

**Issue by Ryuu22** [RyuuSukeChan/ProjectDungeon#25]
Create the basic mechanics of the player, functionals and ready to test.

- [x] Make player able to move to every direction and collide with props and walls.
- [x] Must make use of axis for an smooth movement.
- [x] Player Dash
- [x] Player Primary Attack
- [x] Player Secondary Attack

**EXPECTED RESULT:**

_Player Collisions in [Player.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/Player.cs#L61)_

_Player Movement in [Player.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/Player.cs#L48)_

_Get the axis of the inputs in [InputMaster.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Masters/InputMaster.cs#L28)_

_Player Dash in [Player.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/Player.cs#L105)_

_Player Primary Attack in [Player.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/Player.cs#L76)_

_Player Secondary Attack in [Player.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/Player.cs) and [PlayerArrow.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Player/PlayerArrow.cs)_

**Comment by Nisew** [comment]
Implemented player Movement in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/b0683788bf8f4738edc197fd11d65ada0abf9dbf

**Comment by Nisew** [comment]
Implemented player Dash in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/c3e0640a3a7f3ea7071d4f049a8a152cef3976f6

**Comment by Nisew** [comment]
Implemented player Primary Attack in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/2cf3df90aaaf420db9a9fc702f3d0925742387bd

**Comment by Nisew** [comment]
Implemented player Collisions with terrain in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/c60893023a0fe36958fabc6371fbe7a3fd7c61d2

**Comment by Nisew** [comment]
Implemented player Secondary Attack in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/af5151cec49abf301238819d62984f128181e589
