### ISSUE TITLE
Create An Artificial Intelligence For Enemies

### ISSUE THREAD

**Issue by Ryuu22** [RyuuSukeChan/ProjectDungeon#26]
Enemies must have a yet simple but effective AI for their behaviour and interaction with the player.

- [x] Slime
- [x] Passive Slime
- [x] Spitter Slime
- [x] Boss Slime

**EXPECTED RESULT:**

_Slime behaviour script in [Slime.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Enemies/Slime.cs)_

_Passive Slime behaviour in [PassiveSlime.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Enemies/PassiveSlime.cs)_

_Spitter Slime behaviour script in [SpitterSlime.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Enemies/SpitterSlime.cs)_

_Boss behaviour script in [Boss.cs](insert link of the script when finished)_

**Comment by RyuuSukeChan** [comment]
- [ ] Slime

**Comment by Nisew** [comment]
Spitter Slime added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/e92039b4005992b202eeb93fb6627aedb159e2ef

**Comment by Nisew** [comment]
Passive Slime added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/293d19352f69a6e7ea33d9d7caf9c185d1a1ceb4

**Comment by Nisew** [comment]
Slime added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/3f12c8a90c5ad6235674040066990a7c2381ae1e
Slime Reworked in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/2aadde037b1d2d51a704d3136b4f0564f76cc67f

**Comment by Nisew** [comment]
Boss implemented in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/5d8831ef89c4f0927964098e39a82ae2c923a2c9
