### ISSUE TITLE
Draw Level Design Map

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#34]
Create an image of the level (max 4096x4096) detailed and with a legend that explains the elements included.
Generate a clone of this image to create a flow map.

- [x] Design the level
- [x] Create the image
- [x] Create the legend
- [x] Flow map

**EXPECTED RESULTS:**

_Level Design Map and Legend -_

_mapLevel01.png_
_mapLegend.png_
_flowMap.png_

_Map LevelDesign in [mapLevel01.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/mapLevel01.png)_

_Map Legend in [mapLegend.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/mapLegend.png)_

_FlowMap in [flowMap.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/flowMap.png)_

**Comment by dandraws21** [comment]
Uploaded LevelDesign and Level Legend map in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/650b1387eb1eb3cd52f289d6b52af2d1e0e2d6fb

**Comment by dandraws21** [comment]
Uploaded Flow map in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/6b0f3f7d1e13b1f315003f643023a5878e7e7d6d
