### ISSUE TITLE
Draw All Character Thumbnails

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#36]
Image showing 12 character thumbnails of player/enemies/characters. A brainstorming of new ideas and concepts to do.

- [x] Albert (6) - Character Thumbnails
- [x] Dani (6) - Character Thumbnails

**EXPECTED RESULT:**

_Get an image showing 12 character thumbnails, named [characterThumbnails.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/characterThumbnails.png)_

**Comment by dandraws21** [comment]
Uploaded Character Thumbnails in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/9f6618e815cd2a164d541b8af2854eb08b599e34
