### ISSUE TITLE
Draw Characters Size Chart

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#38]
Image showing in a grid the various sizes of the enemies compared with the player.
It should be organized from shorter to taller from left to right.

- [x] Character Measures (image)

**EXPECTED RESULT:**

_Get a .png showing the relation of character sizes._

_characterMeasures.png_

_Character Measures in [characterMeasures.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/characterMeasures.png)_

**Comment by dandraws21** [comment]
Uploaded Character Measures image in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/d2e9aca41c3b57096b9d58a023e80956eb22e336
