### ISSUE TITLE
Create Title Screen Scene

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#41]
Create the title screen with final art, transitions between scenes and animated.
Create the buttons Game Start, Options and Exit.

- [x] Title final art
- [x] Buttons
- [x] BackGround
- [x] Transition
- [x] Animation

**EXPECTED RESULT:**

_A scene named [TitleScreen.unity](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scenes/TitleScene.unity)_

**Comment by Nisew** [comment]
Buttons added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/9431619ec520e0b16f0c7d35231bad507afdd46a

**Comment by Nisew** [comment]
Buttons animations added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/80ef805d8bd957df9e6bda8c4d1d12a8337cce8b

**Comment by neut1** [comment]
Final Title art added in commit f39a9c081b40a74f8180807d749620ed08c66bde

**Comment by Nisew** [comment]
Background and buttons art implemented in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/2d347e93423ec4e245965e31d3141f1f5fbd9b53
