### ISSUE TITLE
Create The Ending Screen Scene

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#43]
Create the ending screen with a panel and basic messages of victory or defeat.
The gameplay must have Victory and Defeat conditions in order to show this screen.

- [x] Background
- [x] Victory or Defeat messages

**EXPECTED RESULTS:**

_endingBackground.png_
_winEnding.png_
_loseEnding.png_

_Win image in [winEnding.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/winEnding.png)_

_Lose image in [loseEnding.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/loseEnding.png)_

**Comment by dandraws21** [comment]
Lose and Win images added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/79657667eaad36c15746daafafdf1b9e1c4a0e7d
