### ISSUE TITLE
Gameplay Screen - Place Enemies

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#44]
Create an enemies and a boss to be implemented in the ALPHA version of the gameplay screen. Optional to create animations.

- [x] Pasive Slime (animation optional)
- [x] Melee Slime (animation optional)
- [x] Ranged Slime (animation optional)
- [x] Slime Boss (texture optional)

**EXPECTED RESULTS:**

_Create enemy sprites to implement in the gameplay screen:_

_Pasive -_
_enemyPasiveSlime.png_

_Pasive Slime in [enemyPasiveSlime.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/Enemies/enemyPasiveSlime.png)_

_(optional) enemyPasiveSlimeWalk.png_
_(optional) enemyPasiveSlimeAttack.png_
_(optional) enemyPasiveSlimeDeath.png_

_Melee -_
_enemyMeleeSlime.png_

_Melee Slime in [enemyMeleeSlime.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/Enemies/enemyMeleeSlime.png)_

_(optional) enemyMeleeSlimeWalk.png_
_(optional) enemyMeleeSlimeAttack.png_
_(optional) enemyMeleeSlimeDeath.png_

_Ranged -_
_enemyRangedSlime.png_

_Ranged Slime in [enemyRangedSlime.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/ArtSources/Enemies/enemyRangedSlime.png)_

_(optional) enemyRangedSlimeWalk.png_
_(optional) enemyRangedSlimeAttack.png_
_(optional) enemyRangedSlimeDeath.png_

_Boss -_
_bossSlime.png_

**Comment by dandraws21** [comment]
Uploaded Pasive, Melee and Ranged Slime place-holder in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/fd82f82bebc397ddb1553694b89913f086700570
