### ISSUE TITLE
Gameplay Screen - Create Level

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#45]
Create a basic level with 8 final art props to test all the mechanics of the game, it can be done out of boxes.

- [x] Level basic shape
- [x] Fill it with elements to test mechanics
- [x] 8 final props implemented

**EXPECTED RESULT:**

_A playable prototype map mounted in the [Gameplay Screen](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scenes/Main.unity)_

**Comment by Ryuu22** [comment]
Map done on commit 167475fed3a1eecb10b6aa3e7cfa993184d6b0be
