### ISSUE TITLE
Gameplay Screen - Implement Particles

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#47]
Create 5 good-looking particle systems in unity that provide a inmmersion in the game and feedback to the player.

- [x] Player Blood
- [x] Common Slime slime (when receives damage)
- [x] Healing Point Particles
- [x] Plant Particles
- [x] Healing Particles

**EXPECTED RESULT:**

_Particle Systems as GameObjects in [Gameplay Screen](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scenes/Main.unity)_

**Comment by Ryuu22** [comment]
Plant Particles implemented on 149c869872f413bb0c9651629a01178d146efefb

**Comment by Nisew** [comment]
Player blood implemented in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/8ddf1f56bc212586910cb04237e1d1511fcb5643
