### ISSUE TITLE
Draw Ending Screen Mockup

### ISSUE THREAD

**Issue by Nisew** [RyuuSukeChan/ProjectDungeon#49]
Create a mockup for the ending screen with the variations if you win or lose. Optional to create transition animations.

- [x] Win (animation optional)
- [x] Lose (animation optional)

**EXPECTED RESULTS:**

_Two Mockups from the ending screen:_

_Win - mockupEndWin.png_
_Lose- mockupEndLose.png_

_Win mockup in [winEnding.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Mockups/winEnding.png)_

_Lose mockup in [loseEnding.png](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Mockups/loseEnding.png)_

**Comment by dandraws21** [comment]
Lose and Win mockups added in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/ae834e6be28d62caccf065c5c1ecaebed1102c79
