### ISSUE TITLE
Code Props and environment elements

### ISSUE THREAD

**Issue by Ryuu22** [RyuuSukeChan/ProjectDungeon#52]
*Barrel & Destructibles*
 - [x] Barrel Prefab
 - [x] Destroy Barrel

*Bridge* 
- [x] Detects Player
- [x] Destroy Bridge

*Plants*
- [x] Gets Hit
- [x] Shoot

*EXPECTED RESULTS*

_A [DestructibleBehaviour.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Environment/DestructibleBehaviour.cs) file that works for every destructible prop in the game, a barrel prefab. A [BridgeBehaviour.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Environment/BridgeBehaviour.cs) file and a bridge prefab that gets destroyed after crossing it._

_The behaviour of the plant in [ShootingPlant.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Environment/ShootingPlant.cs) and [PlantProjectile.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Environment/PlantProjectile.cs)_

**Comment by Ryuu22** [comment]
Added and coded [DestructibleBehaviour.cs](https://github.com/RyuuSukeChan/ProjectDungeon/blob/master/Assets/Scripts/Environment/DestructibleBehaviour.cs) on https://github.com/RyuuSukeChan/ProjectDungeon/commit/3d41f86367498a21cfbf26e810a67c2c8a1e34a2

**Comment by Ryuu22** [comment]
Bridge detects player and gets destroyed applied on https://github.com/RyuuSukeChan/ProjectDungeon/commit/e4e4f1a645f11aec3c76b851d8c5d85d973011d5

**Comment by Nisew** [comment]
Plant Behaviour implemented in commit https://github.com/RyuuSukeChan/ProjectDungeon/commit/e0f56e28fc40ff51a9af5be5cf357b146c668dc4
