### ISSUE TITLE
Draw (temporal)  Hazard Images 

### ISSUE THREAD

**Issue by dandraws21** [RyuuSukeChan/ProjectDungeon#53]
Create an image from each Hazard and Hazard-state. Every image has independent and measures (256x256px).

Need to draw:

- [ ] Spikes (Closed - Warning - Opened)
- [ ] Spawner

**EXPECTED RESULTS:**

_**Hazard images -**_

_spikesOpen.png_
_spikesWarning.png_
_spikesColsed.png_

_spawner.png_

**Comment by Nisew** [comment]
Closed to reopen this in another issue
